<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.540">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting EV Price</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Predicting EV Price_files/libs/clipboard/clipboard.min.js"></script>
<script src="Predicting EV Price_files/libs/quarto-html/quarto.js"></script>
<script src="Predicting EV Price_files/libs/quarto-html/popper.min.js"></script>
<script src="Predicting EV Price_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Predicting EV Price_files/libs/quarto-html/anchor.min.js"></script>
<link href="Predicting EV Price_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Predicting EV Price_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Predicting EV Price_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Predicting EV Price_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Predicting EV Price_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting EV Price</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this project, I will be creating a model to predict the prices of electric vehicles (in USD) based on variables such as battery capacity, acceleration, top speed, range, efficiency, fast charge speed, drive, and number of seats.</p>
</section>
<section id="data-description" class="level1">
<h1>Data Description</h1>
<p>This dataset has 177 observations with 9 variables. 1. Battery Capacity (numeric) 2. Acceleration (numeric) 3. Top Speed (numeric) 4. Range (numeric) 5. Efficiency (numeric) 6. Fast Charge Speed (numeric) 7. Drive (categorical) 8. Number of Seats (categorical) 9. Price in USD (numeric)</p>
<section id="head-of-dataset" class="level2">
<h2 class="anchored" data-anchor-id="head-of-dataset">Head of Dataset</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  battery_capacity acceler…¹ top_s…² range effic…³ fast_…⁴ drive numbe…⁵ price…⁶
             &lt;dbl&gt;     &lt;dbl&gt;   &lt;int&gt; &lt;int&gt;   &lt;int&gt;   &lt;int&gt; &lt;dbl&gt;   &lt;int&gt;   &lt;dbl&gt;
1             58         7.3     150   335     173     210     2       5  45999.
2             31        22.4     130   160     194      NA     2       5  38016 
3             36         7.9     144   220     164     230     2       5  31194 
4             86.5       5.7     200   375     231     600     1       5  95880 
5             83.7       2.8     260   390     215     860     1       4 166596 
6             36        14       123   165     218     170     2       7  36306 
# … with abbreviated variable names ¹​acceleration, ²​top_speed, ³​efficiency,
#   ⁴​fast_charge_speed, ⁵​number_of_seats, ⁶​price_in_us</code></pre>
</div>
</div>
</section>
<section id="dataset-summary" class="level2">
<h2 class="anchored" data-anchor-id="dataset-summary">Dataset Summary</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> battery_capacity  acceleration      top_speed       range         efficiency    fast_charge_speed     drive       number_of_seats  price_in_us    
 Min.   : 16.70   Min.   : 2.100   Min.   :123   Min.   : 95.0   Min.   :104.0   Min.   : 120.0    Min.   :1.000   Min.   :2.000   Min.   : 21924  
 1st Qu.: 45.00   1st Qu.: 5.500   1st Qu.:150   1st Qu.:260.0   1st Qu.:168.0   1st Qu.: 290.0    1st Qu.:1.000   1st Qu.:5.000   1st Qu.: 37800  
 Median : 66.50   Median : 7.500   Median :160   Median :340.0   Median :189.0   Median : 440.0    Median :2.000   Median :5.000   Median : 54174  
 Mean   : 65.67   Mean   : 7.802   Mean   :177   Mean   :339.2   Mean   :194.6   Mean   : 485.5    Mean   :1.893   Mean   :5.175   Mean   : 61514  
 3rd Qu.: 77.40   3rd Qu.: 9.500   3rd Qu.:200   3rd Qu.:400.0   3rd Qu.:216.0   3rd Qu.: 600.0    3rd Qu.:3.000   3rd Qu.:5.000   3rd Qu.: 69962  
 Max.   :200.00   Max.   :22.400   Max.   :410   Max.   :970.0   Max.   :281.0   Max.   :1410.0    Max.   :3.000   Max.   :7.000   Max.   :226800  
                                                                                 NA's   :5                                                         </code></pre>
</div>
</div>
</section>
<section id="correlation-matrix-includes-y" class="level2">
<h2 class="anchored" data-anchor-id="correlation-matrix-includes-y">Correlation Matrix (includes Y)</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  battery_capacity acceleration   top_speed       range  efficiency fast_charge_speed       drive number_of_seats price_in_us
battery_capacity         1.0000000   -0.6161240  0.68646467  0.88847790  0.34886536                NA -0.41253888      0.12557524  0.70021707
acceleration            -0.6161240    1.0000000 -0.81828960 -0.70778045  0.15614859                NA  0.46204445      0.33324436 -0.54858909
top_speed                0.6864647   -0.8182896  1.00000000  0.75688015 -0.05902354                NA -0.45233581     -0.25453321  0.76269832
range                    0.8884779   -0.7077804  0.75688015  1.00000000 -0.08388001                NA -0.32897233     -0.07879452  0.66648067
efficiency               0.3488654    0.1561486 -0.05902354 -0.08388001  1.00000000                NA -0.25848770      0.59961703  0.26849720
fast_charge_speed               NA           NA          NA          NA          NA                 1          NA              NA          NA
drive                   -0.4125389    0.4620444 -0.45233581 -0.32897233 -0.25848770                NA  1.00000000     -0.09465541 -0.51721581
number_of_seats          0.1255752    0.3332444 -0.25453321 -0.07879452  0.59961703                NA -0.09465541      1.00000000 -0.01148547
price_in_us              0.7002171   -0.5485891  0.76269832  0.66648067  0.26849720                NA -0.51721581     -0.01148547  1.00000000</code></pre>
</div>
</div>
</section>
<section id="linearity-of-y-v.-predictors" class="level2">
<h2 class="anchored" data-anchor-id="linearity-of-y-v.-predictors">Linearity of Y v. Predictors</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Predicting-EV-Price_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="distribution-of-predictors-y" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-predictors-y">Distribution of Predictors + Y</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Predicting-EV-Price_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="models" class="level1">
<h1>Model(s)</h1>
<section id="model-1-full-model-no-transformations" class="level2">
<h2 class="anchored" data-anchor-id="model-1-full-model-no-transformations">Model 1 (Full Model, No Transformations)</h2>
<p>price_in_us ~ (battery_capacity + acceleration + top_speed + range + efficiency + fast_charge_speed + drive + number_of_seats</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price_in_us ~ (battery_capacity + acceleration + 
    top_speed + range + efficiency + fast_charge_speed + drive + 
    number_of_seats), data = ev_cars)

Residuals:
   Min     1Q Median     3Q    Max 
-39394  -8053  -1104   4860  67594 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -2.199e+05  2.285e+04  -9.622  &lt; 2e-16 ***
battery_capacity  -1.897e+03  3.118e+02  -6.085 8.05e-09 ***
acceleration       3.267e+03  9.127e+02   3.579 0.000454 ***
top_speed          4.866e+02  5.890e+01   8.262 4.70e-14 ***
range              4.620e+02  6.444e+01   7.169 2.50e-11 ***
efficiency         1.014e+03  1.244e+02   8.151 9.07e-14 ***
fast_charge_speed  2.417e+00  8.639e+00   0.280 0.779950    
drive             -7.378e+03  1.877e+03  -3.930 0.000125 ***
number_of_seats   -9.022e+03  1.935e+03  -4.662 6.49e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14920 on 163 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.7955,    Adjusted R-squared:  0.7854 
F-statistic: 79.24 on 8 and 163 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Predicting-EV-Price_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>bcPower Transformations to Multinormality 
   Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd
Y1   -0.6817        -0.5      -0.9277      -0.4357
Y2    0.0033         0.0      -0.0020       0.0087
Y3    0.4054         0.5       0.1916       0.6191
Y4   -1.0828        -1.0      -1.5060      -0.6595
Y5    0.0049         0.0      -0.0012       0.0110
Y6    0.0112         0.0      -0.0028       0.0253
Y7   -0.0521         0.0      -0.2491       0.1449
Y8   -0.5047        -0.5      -0.9337      -0.0758
Y9   -0.9642        -1.0      -1.6992      -0.2292

Likelihood ratio test that transformation parameters are equal to 0
 (all log transformations)
                                           LRT df       pval
LR test, lambda = (0 0 0 0 0 0 0 0 0) 71.35114  9 8.2684e-12

Likelihood ratio test that no transformations are needed
                                           LRT df       pval
LR test, lambda = (1 1 1 1 1 1 1 1 1) 1749.079  9 &lt; 2.22e-16</code></pre>
</div>
</div>
<p>The first model is a simple linear regression model that includes the following variables as predictors for price_in_us with no transformation to both X nor Y: battery_capacity, acceleration, top_speed, range, efficiency, fast_charge_speed, drive, and number_of_seats. The summary of this model tells us that the fast_charge_speed is a statistically insignificant predictor of price, given by its high p-value (0.779950). It is also worth noting that the adjusted R squared is 0.7854, meaning that around 78.5% of the variance in the price_in_us variable can be explained by the predictors. From the diagnostic plots, although there is no non-linear pattern in the residuals plot, there is a slight showing of heteroscedasticity in the Residuals vs Fitted plot. The Normal Q-Q plot suggests that despite the presence of a few points that appear to need further investigation, the residuals are generally normally distributed. Another notable observation is the presence of high leverage points (Ex: Point 59) and outliers (Ex: Point 19) in the Residuals vs Leverage plot. From these key takeaways, it can be concluded that a transformation of variables may be necessary.</p>
</section>
<section id="model-2" class="level2">
<h2 class="anchored" data-anchor-id="model-2">Model 2</h2>
<p>price_in_us^(-0.5) ~ log(battery_capacity) + acceleration^(0.5) + 1/top_speed + log(efficiency) + log(range) + log(drive) + 1/number_of_seats</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = t_price ~ t_bat + t_acc + t_tspeed + t_range + t_eff + 
    t_drive + t_seats)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.437e-03 -2.647e-04  5.385e-05  2.681e-04  1.261e-03 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.5121752  0.1682443  -3.044 0.002706 ** 
t_bat       -0.0773229  0.0243689  -3.173 0.001792 ** 
t_acc       -0.0002576  0.0001780  -1.447 0.149639    
t_tspeed     0.3302845  0.0820974   4.023 8.65e-05 ***
t_range      0.0763017  0.0243678   3.131 0.002052 ** 
t_eff        0.0748235  0.0243573   3.072 0.002480 ** 
t_drive      0.0004179  0.0001081   3.865 0.000158 ***
t_seats     -0.0002148  0.0010159  -0.211 0.832830    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.000465 on 169 degrees of freedom
Multiple R-squared:  0.7664,    Adjusted R-squared:  0.7567 
F-statistic: 79.19 on 7 and 169 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The second linear regression model includes the following transformed variables as predictors for the inverse square-root of price_in_us: log of battery_capacity, square root of acceleration, inverse of top_speed, log of efficiency, log of range, log of drive, and the inverse of number_of_seats. All their corresponding powers are determined by the estimated powers of the Box-Cox transformation. Though the model’s p-value is below 005 (&lt;2.2e-16), its adjusted R-squared value is 0.7567 and the model summary shows that there aretwo transformed variables that are not statistically significant: acceleration and number of seats. Even with transformations applied to every variable, it is worth noting that the best course of action is to perform variable selection in order to make a more appropriate model.</p>
</section>
<section id="model-3-final-and-best-model-with-lowest-aic" class="level2">
<h2 class="anchored" data-anchor-id="model-3-final-and-best-model-with-lowest-aic">Model 3 (Final and Best Model with Lowest AIC)</h2>
<p>price_in_us^(-0.5) ~ log(battery_capacity) + log(range) + 1/top_speed + log(efficiency)</p>
<section id="backwards-aic" class="level3">
<h3 class="anchored" data-anchor-id="backwards-aic">Backwards AIC</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-2708.57
t_price ~ t_bat + t_acc + t_tspeed + t_range + t_eff + t_drive + 
    t_seats

           Df  Sum of Sq        RSS     AIC
- t_seats   1 9.7000e-09 3.6556e-05 -2710.5
&lt;none&gt;                   3.6547e-05 -2708.6
- t_acc     1 4.5300e-07 3.7000e-05 -2708.4
- t_eff     1 2.0407e-06 3.8587e-05 -2701.0
- t_range   1 2.1203e-06 3.8667e-05 -2700.6
- t_bat     1 2.1772e-06 3.8724e-05 -2700.3
- t_drive   1 3.2307e-06 3.9777e-05 -2695.6
- t_tspeed  1 3.5001e-06 4.0047e-05 -2694.4

Step:  AIC=-2710.53
t_price ~ t_bat + t_acc + t_tspeed + t_range + t_eff + t_drive

           Df  Sum of Sq        RSS     AIC
&lt;none&gt;                   3.6556e-05 -2710.5
- t_acc     1 4.4420e-07 3.7001e-05 -2710.4
- t_eff     1 2.0313e-06 3.8588e-05 -2702.9
- t_range   1 2.1108e-06 3.8667e-05 -2702.6
- t_bat     1 2.1676e-06 3.8724e-05 -2702.3
- t_drive   1 3.2406e-06 3.9797e-05 -2697.5
- t_tspeed  1 3.6515e-06 4.0208e-05 -2695.7</code></pre>
</div>
</div>
</section>
<section id="forward-aic" class="level3">
<h3 class="anchored" data-anchor-id="forward-aic">Forward AIC</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-2465.22
t_price ~ 1

           Df  Sum of Sq        RSS     AIC
+ t_bat     1 1.0103e-04 5.5395e-05 -2647.0
+ t_range   1 6.9149e-05 8.7275e-05 -2566.5
+ t_tspeed  1 6.8600e-05 8.7824e-05 -2565.4
+ t_acc     1 5.7796e-05 9.8628e-05 -2544.8
+ t_eff     1 2.9438e-05 1.2699e-04 -2500.1
&lt;none&gt;                   1.5642e-04 -2465.2

Step:  AIC=-2646.96
t_price ~ t_bat

           Df  Sum of Sq        RSS     AIC
+ t_range   1 3.6904e-06 5.1705e-05 -2657.2
+ t_eff     1 3.6395e-06 5.1756e-05 -2657.0
+ t_tspeed  1 3.3575e-06 5.2038e-05 -2656.0
+ t_acc     1 1.8306e-06 5.3565e-05 -2650.9
&lt;none&gt;                   5.5395e-05 -2647.0

Step:  AIC=-2657.16
t_price ~ t_bat + t_range

           Df  Sum of Sq        RSS     AIC
+ t_tspeed  1 1.0050e-05 4.1655e-05 -2693.4
+ t_acc     1 6.5397e-06 4.5165e-05 -2679.1
+ t_eff     1 1.9706e-06 4.9734e-05 -2662.0
&lt;none&gt;                   5.1705e-05 -2657.2

Step:  AIC=-2693.42
t_price ~ t_bat + t_range + t_tspeed

        Df  Sum of Sq        RSS     AIC
+ t_eff  1 1.8578e-06 3.9797e-05 -2699.5
&lt;none&gt;                4.1655e-05 -2693.4
+ t_acc  1 4.2600e-09 4.1651e-05 -2691.4

Step:  AIC=-2699.49
t_price ~ t_bat + t_range + t_tspeed + t_eff

        Df  Sum of Sq        RSS     AIC
&lt;none&gt;                3.9797e-05 -2699.5
+ t_acc  1 4.5397e-11 3.9797e-05 -2697.5</code></pre>
</div>
</div>
</section>
<section id="final-model" class="level3">
<h3 class="anchored" data-anchor-id="final-model">Final Model</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = t_price ~ t_bat + t_range + t_tspeed + t_eff)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.994e-03 -3.243e-04  5.233e-05  2.691e-04  1.502e-03 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.48783    0.17342  -2.813  0.00548 ** 
t_bat       -0.07394    0.02511  -2.945  0.00368 ** 
t_range      0.07296    0.02511   2.905  0.00415 ** 
t_tspeed     0.31468    0.04802   6.554 6.29e-10 ***
t_eff        0.07112    0.02510   2.834  0.00515 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.000481 on 172 degrees of freedom
Multiple R-squared:  0.7456,    Adjusted R-squared:  0.7397 
F-statistic:   126 on 4 and 172 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Predicting-EV-Price_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>After variable selection, Model 3 is seen to be our “best” predictive model, as this model reduces the number of predictor variables to prevent overfitting the data as well as removing many predictor variables that were identified as victims of multicollinearity. Moreover, all of the predictor variables in this model are significant while also not violating the model assumptions. Additionally, our high R2 value indicates a good fit of the model to the data and the F - test for overall model significance gives a p - value close to 0, indicating that the final model is valid. Looking at the diagnostic plots, one can see that the final model has relatively constant variance across its fitted values. Also, the Normal Q-Q plot follows a relatively linear trend, which indicates that the model assumption of Normality is satisfied as well. It is worth noting that observation 19 is an extreme outlier in our diagnostic plots and, thus, does stray heavily from the overall model pattern; however, there is little that can be done besides removing this observation from the data, as it is an extreme outlier of the data, with a standardized residual value close to -8. Even transforming the data could do little to fix the extremeness of this data point.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>